version: '3.0'
services:
  rasa-flask:
    image: rasa:latest-full
    build:
      context:  .
      dockerfile: Dockerfile
    container_name: rasa-chat-app
    volumes: 
      - .:/app
    ports:
      - 5000:5000
    command: python3 app.py
  rasa-server:
    image: rasa/rasa
    container_name: rasa-server
    volumes: 
      - .:/app
    ports:
      - 5005:5005
    command: run -m models --enable-api --cors "*"
    

